version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: unit_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - runit_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: runit_backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/runit
      MERCADOPAGO_ACCESS_TOKEN: ${MERCADOPAGO_ACCESS_TOKEN}
      FRONTEND_URL: http://localhost
      NODE_ENV: development
    networks:
      - runit_network
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./run-it
      dockerfile: Dockerfile
    container_name: runit_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - runit_network

volumes:
  mongo_data:

networks:
  runit_network:
    driver: bridge